init model
Training...
Epoch 1 started
  0%|                                                                                                                                                                        | 0/938 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/nvme1/data_rt/LR/flops/train_mlp.py", line 68, in <module>
    trainer.train()
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 104, in train
    global_step = self.step(epoch, global_step)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 202, in step
    loss, output = self.zo_step_all_params(self.model, data, target, self.sample_n)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 342, in zo_step_all_params
    loss1, _ = self.zo_forward(model, data, target)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 319, in zo_forward
    loss, output = self.compute_loss(model, data, target)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 285, in compute_loss
    output, _ = model(data)
  File "/home/rt/data/miniconda3/envs/LR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rt/data/miniconda3/envs/LR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nvme1/data_rt/LR/flops/models/my_mlp_modeling.py", line 39, in forward
    x = self.acti(self.fc1(x, add_noise=add_noise))
  File "/home/rt/data/miniconda3/envs/LR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rt/data/miniconda3/envs/LR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nvme1/data_rt/LR/flops/models/modules.py", line 58, in forward
    logit_output = super().forward(input)
  File "/home/rt/data/miniconda3/envs/LR/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
