init model
Training...
Epoch 1 started
  0%|                                                                                                                                                                                 | 0/938 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/nvme1/data_rt/LR/flops/train_mlp.py", line 23, in <module>
    trainer.train()
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 104, in train
    global_step = self.step(epoch, global_step)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 128, in step
    loss, output = self.zo_step_all_params_allocator(self.model, data, target, self.sample_n)
  File "/nvme1/data_rt/LR/flops/trainer_a.py", line 263, in zo_step_all_params_allocator
    bernoulli_dataloader = bernoulli_allocater(data, target, loss_values, sample_budget, 0.5)
  File "/nvme1/data_rt/LR/flops/allocator.py", line 92, in bernoulli_allocater
    data = data.repeat_interleave(allocated_budget, dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
